<?xml version="1.0" encoding="UTF-8"?>
<testrun name="UserServiceTest" project="spring30-5.1.1" tests="2" started="2" failures="0" errors="2" ignored="0">
  <testsuite name="springbook.user.service.UserServiceTest" time="7.938">
    <testcase name="add" classname="springbook.user.service.UserServiceTest" time="6.97">
      <error>org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: The Network Adapter could not establish the connection&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:518)&#13;
	at springbook.user.dao.UserDaoJdbc.deleteAll(UserDaoJdbc.java:50)&#13;
	at springbook.user.service.UserServiceTest.add(UserServiceTest.java:91)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.sql.SQLException: The Network Adapter could not establish the connection&#13;
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:412)&#13;
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:531)&#13;
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:221)&#13;
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)&#13;
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:503)&#13;
	at org.springframework.jdbc.datasource.SimpleDriverDataSource.getConnectionFromDriver(SimpleDriverDataSource.java:140)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)&#13;
	... 33 more&#13;
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection&#13;
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:359)&#13;
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:422)&#13;
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:672)&#13;
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:237)&#13;
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1042)&#13;
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:301)&#13;
	... 42 more&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.PlainSocketImpl.socketConnect(Native Method)&#13;
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)&#13;
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)&#13;
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)&#13;
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)&#13;
	at java.net.Socket.connect(Socket.java:529)&#13;
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:141)&#13;
	at oracle.net.nt.ConnOption.connect(ConnOption.java:123)&#13;
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:337)&#13;
	... 47 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="upgradeLevels" classname="springbook.user.service.UserServiceTest" time="0.927">
      <error>org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: The Network Adapter could not establish the connection&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:518)&#13;
	at springbook.user.dao.UserDaoJdbc.deleteAll(UserDaoJdbc.java:50)&#13;
	at springbook.user.service.UserServiceTest.upgradeLevels(UserServiceTest.java:51)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.sql.SQLException: The Network Adapter could not establish the connection&#13;
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:412)&#13;
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:531)&#13;
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:221)&#13;
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)&#13;
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:503)&#13;
	at org.springframework.jdbc.datasource.SimpleDriverDataSource.getConnectionFromDriver(SimpleDriverDataSource.java:140)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)&#13;
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)&#13;
	... 33 more&#13;
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection&#13;
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:359)&#13;
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:422)&#13;
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:672)&#13;
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:237)&#13;
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1042)&#13;
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:301)&#13;
	... 42 more&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.PlainSocketImpl.socketConnect(Native Method)&#13;
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)&#13;
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)&#13;
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)&#13;
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)&#13;
	at java.net.Socket.connect(Socket.java:529)&#13;
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:141)&#13;
	at oracle.net.nt.ConnOption.connect(ConnOption.java:123)&#13;
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:337)&#13;
	... 47 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
